CREATE TABLE IF NOT EXISTS users (
    ID SERIAL PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    passwordHash TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS projects (
    ID SERIAL PRIMARY KEY,
    creatorID INTEGER NOT NULL,
    name TEXT NOT NULL,
    description TEXT NOT NULL,
    FOREIGN KEY (creatorID) REFERENCES users (ID) ON DELETE CASCADE
);
